### ISSUE TITLE
[Bug]: action is defaulting to calculate for everything

### ISSUE THREAD

**Issue by greay** [quicksilver/Quicksilver#2963]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

in the latest Quicksilver, the default action for everything, even applications, is "Calculate". The rank for "Run" is 1 and the rank for "Calculate" is set to 4, so it's definitely jumping priority for some reason.

### Steps to reproduce

1. open quickilver
2. start typing an application, e.g. "texted"
3. See TextEdit pop up with "Calculate"

### Expected behavior

Calculate should only show for numeric expressions

### MacOS Version

macOS 13

### Quicksilver Version

2.4.1 (4040)

### Relevant Plugins

Calculator 2.3.5

**Comment by Proggie** [comment]
Happening to me too. Seems the "Launch" action is missing.

**Comment by n8henrie** [comment]
@greay Could you try running the debug version from [here](https://github.com/quicksilver/Quicksilver/actions/runs/6363050382) and see whether or not the unwanted behavior changes?

**Comment by anths** [comment]
Same; consistently observed on two systems on different macOS versions (13.5 and... something older, 11 I think?). That debug build does not seem to help.

**Comment by apotek** [comment]
Same issue here. Both my user accounts on Mac OS Ventura exhibit this behavior, as well as my account on a Mac OS Catalina laptop. Have used QSApp since its early releases. Calculate is not only the default action for me, but no other action can be selected. I am unable to open apps with QSApp. I type in "Sa" and Safari pops up, but the default action is Calculate and when I try to select a different action, I can't. Hitting return just gives a message like "Cannot calculate..."

**Comment by eggdropsoap** [comment]
For what it's worth, I *can* select other actions: If I summon Quicksilver and type <kbd>s</kbd><kbd>a</kbd> (e.g. for Safari) <kbd>tab</kbd> <kbd>o</kbd><kbd>p</kbd>, the **Open** action replaces **Calculate** and I can launch programs. Other actions work that way too.

I only ever use full keyboard interaction with Quicksilver, so I'm not sure what mouse interactions are or aren't working. For example if I try to click on Calculate instead, it doesn't do anything useful, but I don't know if it's suppose to.

**Comment by greay** [comment]
Using the debug buld, and after re-enabling the Calculator plugin, I still get **Calculate** as the default action for everything.

**Comment by Proggie** [comment]
I fixed by going into the preferences and under Actions, I dragged the Open action above the Calculate action.

**Comment by anths** [comment]
Moving things in the Actions list didn't make any change for me, but I've found a workaround which does. If I select an application, I can tab over to the actions, hit down arrow to get the list, control-click on "Open", and select "Make default", it restores the expected behavior. It's important that you not type "O" or anything else to select for "Open" first, just find it in the list. This has survived restarts of Quicksilver.

Still a bug as it's not respecting what the Actions preference tells it (and is a regression from previous versions), but this workaround works for me.

**Comment by n8henrie** [comment]
@anths -- reordering actions seems to work fine here. Did you remember to relaunch quicksilver after changing the order?

**Comment by MtnCat** [comment]
Having the same issue--both on an earlier OS and still on Sonoma. Have reinstalled QS, have reordered actions (Calculate #20 now) and relaunched. Does not resolve the issue. Per some of the comments above, I have the ability to select the appropriate action but QS will not learn it--it defaults to calculate for everything, all the time. Missing all the power of QS if I have to select the action each time.

**Comment by n8henrie** [comment]
@MtnCat can you confirm QS version?

Can you give a concrete example with something that should be installed by default -- for example, "Safari" first tab defaults to "open"?

**Comment by MtnCat** [comment]
Hi—thanks for getting back to me.

QS 2.4.2

I’m often trying to open a file, so I type “Hours” which has learned what file I mean (that’s part of the full filename: HoursALR) and so it pops the correct file in the first frame. The associated action should be “Open” but instead it’s “Calculate”—and it never learns to be anything else. No matter what file I start to type in the first frame, the action I get is “calculate” —then I have to tab to that second frame and start to type the correct action and select it (so I can still access the correct action).

It used to remember that for Hours, I wanted to Open and so it would automatically populate HoursALR in the first frame and Open in the second frame and I could just hit enter.

Is that a clear enough description?

This also happens for applications, not just files, in the first frame. I type Chr…and it drops in Chrome, but the associated action is Calculate instead of Open.

However... if I start typing a URL in the first frame, it defaults the action to Open URL, which is correct (it doesn’t try to Calculate)

I have checked the actions in the QS settings—I moved Calculate to #20 on the list, far below Open…and relaunched QS. Doesn’t fix it. 

LMK if you need other details.

Thanks! D.

**Comment by n8henrie** [comment]
Try this:
- shut down QS
- Open a finder window to `~/Library/Application Support/Quicksilver`
- Rename `Actions.plist` to `Actions.plist.bak`
- Restart QS and see if behavior changes

This will lose your actions history unfortunately, but you can un-rename the file if it doesn't change work.

**Comment by MtnCat** [comment]
Looks like this has fixed it!!! Thank you so much.

**Comment by n8henrie** [comment]
Excellent, glad to hear it. NateOn Jan 29, 2024, at 7:46 PM, MtnCat ***@***.***> wrote:﻿
Looks like this has fixed it!!! Thank you so much.

**Comment by ar-rm** [comment]
> Try this:
> 
> * shut down QS
> * Open a finder window to `~/Library/Application Support/Quicksilver`
> * Rename `Actions.plist` to `Actions.plist.bak`
> * Restart QS and see if behavior changes
> 
> This will lose your actions history unfortunately, but you can un-rename the file if it doesn't change work.

🔼 This seems to have worked for me too.

- QS: `2.4.0 (4039)` -> `2.4.3 (4042)`
- Sequoia: `15.0 (24A335)`

This issue, and related ones [^1], kept me from updating beyond `2.4.0`.

Thank you @n8henrie, @pjrobertson, and all of the other developers who keep QS maintained.

[^1]: Related:
    https://github.com/quicksilver/Quicksilver/issues/2960
    https://github.com/quicksilver/Quicksilver/issues/2961

**Comment by scottcc** [comment]
Can confirm (after upgrading to 2.5.2 from a pretty darn old version like 1.4.x or so) that I also had this problem, and the Actions.plist rename worked. In case it's at all helpful, I *suspect* the key differences are either in the `actionPrecedence` dictionary, moving from 1 --> 2.5:

![Image](https://github.com/user-attachments/assets/5e1b3c84-1a18-4409-a972-fa3070fff987)

or the `actionRanking` array:

![Image](https://github.com/user-attachments/assets/c485a527-a0aa-41f3-b2b4-0a132f258e14)

At any rate, I also wanted to also thank everyone who maintains this fantastic product.

**Comment by pjrobertson** [comment]
Thanks scottcc, it's not ideal behaviour, but it sounds like updating from a really old version may have caused problems. Excellent to see your debugging work. I assume that you dragged the order of the 'calculate' action down, and that solved it for you? Again, not ideal that you need to manually do this, but it should work
