### ISSUE TITLE
[Bug]: Current Application (Menu Bar Items…) command to move emails not working

### ISSUE THREAD

**Issue by gabrielparriaux** [quicksilver/Quicksilver#2978]
### Before submitting your bug report, please confirm you have completed the following steps

- [X] Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
- [X] Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
- [X] Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.

### Bug description

I’m using Current Application (Menu Bar Items…)  <?> with a keyboard shortcut in Apple Mail to move emails from my Inbox to different folders.

Since Sonoma update, it doesn't work anymore as intended. I can use the command, but the emails are copied in the selected folder instead of being moved (the original remains in the Inbox).

### Steps to reproduce

1. Call the command Current Application (Menu Bar Items…)  <?> with a keyboard shortcut in Apple Mail
2. Type the name of an email folder and hit return

### Expected behavior

The email should be moved to the selected folder.

### MacOS Version

Other

### Quicksilver Version

2.4.1 (4040)

### Additional info

Apple Sonoma 14.0

**Comment by gabrielparriaux** [comment]
A small update on the subject: 

Two menus coexist in Apple Mail > Message: 

1. move to > [list of all folders] 
2. copy into > [list of all folders]

I can imagine that, using Quicksilver's command `Current Application (Menu Bar Items…) <?>`, it selects the wrong one: _copy into_ and not _move to_, which is the one I would like…

The strange thing is that, when I use this command and then type the name of an existing email folder as a destination, I get only one proposition and it is indicated as "move to [name of the folder]". I don't see a possibility to access to the other menu which would be "copy into [name of the folder]" (see screenshot, in French). 

And it appears that, as a results, it is doing _copy into_ instead of _move to_…

I hope it is clear enough and sorry for the noise!

<img width="675" alt="Capture d’écran 2023-10-13 à 16 24 53" src="https://github.com/quicksilver/Quicksilver/assets/125275/0d9907eb-0964-4e49-a6cc-799e9f07c292">

**Comment by n8henrie** [comment]
Thanks for the update and sorry for the delay in responding.

Right now I'm really focusing on https://github.com/quicksilver/Quicksilver/issues/2971 -- if I can get tests working reliably in CI I think it will help a lot in debugging these issues.

Hang tight, I'll try to look through these soon.

**Comment by gabrielparriaux** [comment]
Unfortunately, the issue is still the same as described now with version 2.5.3 (4046).

**Comment by pjrobertson** [comment]
Thanks for keeping this alive @gabrielparriaux  - I think you may have been on to something with the 'copy to' vs 'move to'. There was a bug where menu items with the same name weren't working properly. This should now be fixed. Can you please click 'update' in Quicksilver to update the User Interface Access plugin to the latest version (2.3.3) or [download it from here](https://github.com/quicksilver/UIAccess-qsplugin/actions/runs/18619999775/artifacts/4308199022) and install. Let me know how it goes!

<img width="2084" height="1354" alt="Image" src="https://github.com/user-attachments/assets/b253a5ce-3a41-4920-aa81-c7e6240a2e7f" />

**Comment by gabrielparriaux** [comment]
Thank you @pjrobertson for your news and for letting me know about this update!

So, for me, it… broke the thing! 😬 I have no more access to the usual menu bar items after the update to 2.3.3 (with the latest QuickSilver 2.5.3 (4046)).

I don’t see my email folders when I’m in Apple Mail, but I can’t find any other Menu bar item in any application 😰.

I post here a screenshot of the behaviour here in Safari. The items that appear in the list seem related to items in my folders, but that’s impossible to get access to any menu bar item from Safari.

Could it be related to a language problem? My OS is in French…

Thank you for helping if you have any idea!

Best, 

Gabriel

<img width="795" height="495" alt="Image" src="https://github.com/user-attachments/assets/a49f5924-35f4-488a-8f48-808d0af691a1" />

**Comment by pjrobertson** [comment]
It seems like there were a few build issues with that build version. Can you try updating again (by clicking the 'update' button within Quicksilver) and then making sure you are using the latest 2.3.4 version?

![Image](https://github.com/user-attachments/assets/1eb38165-909d-43fa-b2c0-fa5546e3ff7f)

**Comment by gabrielparriaux** [comment]
Great, @pjrobertson! I updated the plugin and the bug seems resolved!

And now I have the two actions available: “copy to” and “move to”, for each email folder.

Just one thing: they seem to be reversed! When I do “copy”, it moves the message to the folder without keeping the original in my inbox; and when I do “move”, it copies the message, keeping the original in the inbox!

Is it possible to just put them back in the proper order?

Thanks a lot for your efforts, that’s highly appreciated.

**Comment by pjrobertson** [comment]
Merci Gabriel!

I just tested this and it appears to work correctly for me. Are you sure it’s not a language/spelling issue? It should pick up the names in the language of your system. 

Can you send a screenshot or video of what is happening?

￼

**Comment by gabrielparriaux** [comment]
In fact, the behaviour seems quite unpredictable…

Sometimes, the “copy” menu moves the message instead of copying it. Sometimes, the “move” menu copies the message instead of moving it. Sometimes it behaves correctly. 

But most of the time, both menus (“copy” and “move”) produce the same result (or copying, or moving).

It’s quite random and I can’t understand why it behaves like this…

I could do a small video but I don’t really want to post it online. Is there a way to share it with you only, @pjrobertson?

Thanks a lot for helping!

Gabriel

**Comment by pjrobertson** [comment]
I’ll send you an email privately for you to share

**Comment by pjrobertson** [comment]
Thanks Gabriel for sharing the video. It didn't help a lot and I'm still not 100% sure what the issue is here, but I've made a couple more changes to the plugin. Can you please try downloading this build from here, and seeing if it works?

https://github.com/quicksilver/UIAccess-qsplugin/actions/runs/18985716762/artifacts/4434466142

**Comment by gabrielparriaux** [comment]
Thank you Patrick for this intent.

I downloaded the new version and installed it.

The plugin is working correctly, but for Apple Mail, I don’t have access to the names of the Mailboxes folders anymore.

I can use the plugin to access all the other common menus from the app, but if I type the name of a folder where I would typically move an email, it doesn’t appear in the list.

I have access to other submenus (so it’s not a problem of submenus apparently), but not the mail folders.

All the best,

Gabriel

**Comment by pjrobertson** [comment]
Hi again Gabriel,

I spent some time looking at this today, and unfortunately it seems that Mail does not do a good job of properly exposing the information for these items. I’ve done my best using what I can, and have created a new build which you can download here: 
https://github.com/quicksilver/UIAccess-qsplugin/actions/runs/19001319019/artifacts/4438752817


If this does not work 100% of the time, then unfortunately we will have to put it down to ‘quirks’ with Mail.app

**Comment by gabrielparriaux** [comment]
Hi Patrick,

Thanks again for all your efforts.

I have access to the folder names again with this new version, which is great.

It works pretty well. In four intents to move/copy emails from my inbox, I had once again a strange behaviour where «copy» task was changed into «moved» one… but the others went fine. So, for me, it’s good enough to be able to use it!

Again a lot of thank you and all the best,

Gabriel
